services:
  bingobg:
    build:
      context: .
      dockerfile: Dockerfile
    image: bingobg:latest
    ports:
      - "2005:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
